apiVersion: v1
kind: Secret
metadata:
    name: stash-app
    namespace: stash
type: Opaque
stringData:
    APP_KEY: ENC[AES256_GCM,data:CKC6N254X6KrEVhsjIPMAo5PkwWWdeES1Ct9Ly5XIb8z+psBEAx2xgB5kfLpvJsQQ+0K,iv:L5MNkExuj6uqHrgpMhelFgCRGvtXKatWWszuuDvCfxE=,tag:LD0iawNR0LSewapV7lyL4A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0YUZhdCtXbU52OFdkcnJJ
            VFFhVEx6UklIWlVJOE54VkJwSXdyazZ6cFZZCjdVWUZpbWpSQjBLdWJuSjJ0WVpO
            NFBYQmZocjZFSFo1L3VCWEFseEFEaEkKLS0tIEZjYS9HUGtUcmlHOXpuRSt5OWhJ
            bWJJUDNQQndBNUJCYUNoYkpmRG9QSncKuBsV7JDw3kIcI6I/3zk8UmgsXlmYwsvK
            /VhCK/hf5ZvDSwo/tXvtMo7rn04faXx+xlks7Ca08Dq1pSIXBrzbPg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1svlvvh3e8778dfl20nvkyd2v0zpjz4edg2a9x2yc0eve8j3n0y7q0csvr4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T10:29:25Z"
    mac: ENC[AES256_GCM,data:CshA4cR7T2yPM4NqihJy4aDyV5S6nSAQN8FGU/dUb0qO+EKK3rx7GuoyBL81ZF2EG1Pf7wNCi7kj47Lpcr8z4U6l22tJuxQKa0ypE00/mkIdXdn0zhqZTu5ofAG8Nf0nsN7OojvZvVocJ8YFipB1iqBYESoS4H4foUYOJq01r18=,iv:FtZmZ+DRX5FMEcFLvVZy4UrWbC4FAWXm1e/KR6L9Elg=,tag:AzWgIqoRbMn+qO0Q73T6/g==,type:str]
    version: 3.13.3
