apiVersion: v1
kind: PersistentVolume
metadata:
  name: mautrix-meta-pv
  namespace: synapse
  labels:
    pvc_type: mautrix-meta-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /etc/matrix/meta/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mautrix-meta-pv-claim
  namespace: synapse
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
