apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: synapse-ingress
  namespace: synapse
  annotations:
    kubernetes.io/ingress.class: cloudflare-tunnel
spec:
  rules:
  - host: matrix.ionize13.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: delegation-service
            port:
              number: 80
